### ISSUE TITLE
Creating a connection with a emtpy url will not invoke the error callback

### ISSUE THREAD

**Issue by plcstpierre** [grncdr/node-any-db#69]
parse-db-url will throw an unhandled exception.

It will throw the same exception if it cannot parse the protocol.

==================

let anyDB = require('any-db');

let conn = anyDB.createConnection("", (error) =>{
    console.log("hi");
});

==================

/home/plcstpierre/projects/pl-sql-client/node_modules/any-db/node_modules/parse-db-url/parse-url.js:14
  var adapter = parsed.protocol.replace(':', '')
                               ^
TypeError: Cannot read property 'replace' of null
    at parseDbUrl (/home/plcstpierre/projects/pl-sql-client/node_modules/any-db/node_modules/parse-db-url/parse-url.js:14:32)
    at Object.connect [as createConnection] (/home/plcstpierre/projects/pl-sql-client/node_modules/any-db/index.js:13:23)
    at Object.<anonymous> (/home/plcstpierre/projects/pl-sql-client/src/backend/test.js:47:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

======================

The protocol parsing is also used for loading the module. It will throw an unhandled exception for unknown protocol too.

module.js:338
    throw err;
          ^
Error: Cannot find module 'any-db-mysq'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at getAdapter (/home/plcstpierre/projects/pl-sql-client/node_modules/any-db/index.js:27:10)
    at Object.connect [as createConnection] (/home/plcstpierre/projects/pl-sql-client/node_modules/any-db/index.js:14:17)
    at Object.<anonymous> (/home/plcstpierre/projects/pl-sql-client/src/backend/test.js:47:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by grncdr** [comment]
The first issue (failed URL parsing throws) is somewhat intentional. Given that `createConnection` both returns a value and accepts a callback, the library can't really know the right way to report the error.

Regarding the second issue, that's definitely intentional. If you don't have the right adapter, it absolutely *should* fail.

That being said, overall I now tend to think that `require('any-db')` is a bit of a mistake, for the next iteration of the Any DB API's I plan to remove it. IMO it's more sensible to push the responsibility to the user to require their adapter directly and pass it into e.g. `any-db-pool` or `any-db-transaction`.

**Comment by plcstpierre** [comment]
Maybe the mistake is returning a value then. Why returning a value and having a success callback?

**Comment by grncdr** [comment]
To be honest, I don't remember. It might just be for convenience (e.g. so one can start issuing queries immediately) or because it fits the pattern exposed by the underlying drivers (at least mysql and postgres IIRC).

In any case, if you want to propose a change in the adapter interface, https://github.com/grncdr/node-any-db-adapter-spec is the best place for it.
