### ISSUE TITLE
any-db-postgres doesn't support current pg package

### ISSUE THREAD

**Issue by spollack** [grncdr/node-any-db#85]
pg@7.x and earlier work fine with any-db-postgres; but if you try pg@8.x, it fails. there was a breaking change in the pg API with version 8.

for example, with pg@8.4.1:

```
/example/node_modules/any-db-postgres/index.js:27
  pg.Client.call(this, opts)
            ^

TypeError: Class constructor Client cannot be invoked without 'new'
    at new PostgresConnection (/example/node_modules/any-db-postgres/index.js:27:13)
    at Object.adapter.createConnection (/example/node_modules/any-db-postgres/index.js:19:14)
    at Object.create (/example/node_modules/any-db-pool/index.js:44:15)
    at createResource (/example/node_modules/generic-pool/lib/generic-pool.js:258:13)
    at ensureMinimum (/example/node_modules/generic-pool/lib/generic-pool.js:291:9)
    at new exports.Pool (/example/node_modules/generic-pool/lib/generic-pool.js:464:3)
    at new ConnectionPool (/example/node_modules/any-db-pool/index.js:71:16)
    at Object.createPool (/example/node_modules/any-db/index.js:22:10)
    at Function.Engine.create (/example/node_modules/gesundheit/lib/engine.js:51:20)
    at Object.module.exports [as engine] (/example/node_modules/gesundheit/lib/engine.js:15:24)
...
```

**Comment by grncdr** [comment]
Thanks for the report @spollack 

I currently don't have the bandwidth or time to update any-db-postgres to work with pg version 8, so I've published a new minor version that explicitly depends on `pg@^7.4.3`.
